# Generated by Django 2.2.7 on 2019-12-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('uid', 'version')},
        ),
    ]
