# Generated by Django 2.2.7 on 2019-12-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20191214_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
