# Generated by Django 2.2.7 on 2019-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='user',
        ),
    ]
